fix listMessage
adiwajshing/Baileys pull request #1070
Opened 2021-12-24 12:52 UTC by Pokoke-01

2021-12-27 17:35 UTC, PurpShell requested changes
changes, other than that should be sailing

2021-12-27 17:35 UTC, PurpShell commented on README.md
> +  listType: 1,
```suggestion
```
remove this, explained below

2021-12-27 17:35 UTC, PurpShell commented on src/Types/Message.ts
> +    listType?: proto.ListMessage.ListMessageListType
```suggestion
```
same over here

2021-12-27 17:35 UTC, PurpShell commented on src/Utils/messages.ts
> +			listType: message.listType
```suggestion
			listType: 1
```

to keep everything simple, just make it default to 1. Now there is no need to modify existing code

2021-12-29 16:42 UTC, S0c5 commented
Well, I liked more the previous changes, allow us to have more control over the messages also I don't know if it's a good idea to simplify the objects to build the Messages, given that those abstractions are not well documented and the only reference documentation is the proto code generated, we need to navigate in the code to know where exactly is assembled the message and how is the mapping.

2021-12-30 00:04 UTC, PurpShell commented
> Well, I liked more the previous changes, allow us to have more control over the messages also I don't know if it's a good idea to simplify the objects to build the Messages, given that those abstractions are not well documented and the only reference documentation is the proto code generated, we need to navigate in the code to know where exactly is assembled the message and how is the mapping.

We don't even know other types yet, adi explained it was getting too complex on the readme

this just makes it simple to the point where I can literally hook it up to my API without any processing. (pass in the content as is)


As for docs, look at type `AnyMessageContent`, I'd say clone baileys-md (`git clone https://github.com/adiwajshing/Baileys.git -b multi-device`), then generate the docs (`look at npm run`). 

You will be able to find the docs simple

2021-12-30 13:02 UTC, PurpShell commented
@adiwajshing thoughts?

2021-12-30 13:02 UTC, PurpShell approved these changes
lgtm

2021-12-31 09:47 UTC, adiwajshing commented on src/Utils/messages.ts
> +			listType: 1
Shouldn't this use the number from the ListType enum, instead of hardcoding it like this?

2021-12-31 10:09 UTC, adiwajshing commented on src/Utils/messages.ts
> +			listType: proto.ListMessage.ListMessageListType[1]
Bruh "SINGLE_SELECT" is the name of the property

2021-12-31 10:15 UTC, merged