Add join group by groupInviteMessage
adiwajshing/Baileys pull request #1355
Opened 2022-03-13 13:26 UTC by Schwartzblat

2022-03-14 03:12 UTC, azudindaem requested changes

2022-03-14 03:12 UTC, azudindaem commented on README.md
> +    const response = await sock.groupAcceptInviteV4(groupInviteMessage")
typo 
`const response = await sock.groupAcceptInviteV4("groupInviteMessage")`

2022-03-14 12:46 UTC, Schwartzblat commented on README.md
> +    const response = await sock.groupAcceptInviteV4(groupInviteMessage")
Actually it supposed to be without "" at all :(
Fixed.

2022-03-14 23:29 UTC, azudindaem commented
there is no need to add new functionality to an existing one

2022-03-22 02:44 UTC, ferhacks commented
.

2022-03-24 10:10 UTC, thisfardi approved these changes

2022-03-25 10:48 UTC, merged