added rejectCall function
adiwajshing/Baileys pull request #2010
Opened 2022-08-09 06:42 UTC by RahulKasireddy

Hey there!
I've added rejectCall function so that you can easily reject call, see the example code below

`sock.ev.on('call', (m) => {
    const _call = m[0];
    if (_call.status == 'offer') {
        sock.rejectCall(_call.id);
    }
})`

2022-08-09 12:43 UTC, souravkl11 approved these changes

2022-08-09 13:01 UTC, souravkl11 requested changes
Use 
`authState.creds.me!.id` 
instead of
 `authState.creds.me.id` 
to prevent this error:
`Object is possibly 'undefined'`

2022-08-09 13:54 UTC, RahulKasireddy commented
> Use
> `authState.creds.me!.id`
> instead of
> `authState.creds.me.id`
> to prevent this error:
> `Object is possibly 'undefined'`

Done ✅

2022-08-09 16:19 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +				to: callOfferData[call_id].from,
do explicitly take in the callerId -- if not specified use from callOfferData

2022-08-09 16:20 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +				id: (new Date().getTime() / 1000).toString().replace('.', '-'),
No need to specify the ID if you use query()

2022-08-09 16:20 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +		await sendNode(stanza)
should probably use query here

2022-08-09 16:20 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +	const rejectCall = async(call_id) => {
please camel case params, and add a type

2022-08-09 16:21 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +				to: callOfferData[call_id].from,
would also remove the unnecessary repetition of `callOfferData[call_id].from`

2022-08-10 08:33 UTC, RahulKasireddy commented on src/Socket/messages-recv.ts
> +				to: callOfferData[call_id].from,
Done ✅

2022-08-10 08:33 UTC, RahulKasireddy commented on src/Socket/messages-recv.ts
> +				id: (new Date().getTime() / 1000).toString().replace('.', '-'),
Done ✅

2022-08-10 08:35 UTC, RahulKasireddy commented on src/Socket/messages-recv.ts
> +		await sendNode(stanza)
I didn't get that 😅, could you please help me to understand 🤝?

2022-08-10 08:35 UTC, RahulKasireddy commented on src/Socket/messages-recv.ts
> +	const rejectCall = async(call_id) => {
Done ✅

2022-08-10 08:46 UTC, RahulKasireddy commented on src/Socket/messages-recv.ts
> +				id: (new Date().getTime() / 1000).toString().replace('.', '-'),
I've added id again cause it's not working without passing the id.

2022-08-10 10:23 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +		await sendNode(stanza)
use query() not sendNode

2022-08-10 10:24 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +				id: (new Date().getTime() / 1000).toString().replace('.', '-'),
yes, because the query function adds the ID automatically -- not the sendNode function

2022-08-10 10:24 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +	const rejectCall = async(call_id: string) => {
camelCase call id

2022-08-10 10:24 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +		const _call_offer = (call_id ? callOfferData[call_id] : callOfferData[Object.keys(callOfferData)[0]]);
callId should always be there -- shouldn't have a ternary here

2022-08-10 10:24 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +		const _call_offer = (call_id ? callOfferData[call_id] : callOfferData[Object.keys(callOfferData)[0]]);
Also please camelCase all variables

2022-08-10 10:25 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +		const _call_offer = (call_id ? callOfferData[call_id] : callOfferData[Object.keys(callOfferData)[0]]);
no need to store the full offer here -- since you're only using offer.from

2022-08-14 06:34 UTC, RahulKasireddy commented on src/Socket/messages-recv.ts
> +		await sendNode(stanza)
Done ✅

2022-08-14 06:35 UTC, RahulKasireddy commented on src/Socket/messages-recv.ts
> +	const rejectCall = async(call_id: string) => {
Done ✅

2022-08-14 06:37 UTC, RahulKasireddy commented on src/Socket/messages-recv.ts
> +		const _call_offer = (call_id ? callOfferData[call_id] : callOfferData[Object.keys(callOfferData)[0]]);
Done ✅

2022-08-15 13:49 UTC, officialdittaz commented
i'm waiting for this feature

2022-08-23 05:53 UTC, souravkl11 commented
@adiwajshing

2022-08-23 06:07 UTC, adiwajshing commented on src/Socket/messages-recv.ts
> +				id: (new Date().getTime() / 1000).toString().replace('.', '-'),
please remove, this isn't resolve

2022-08-23 07:05 UTC, RahulKasireddy commented on src/Socket/messages-recv.ts
> +				id: (new Date().getTime() / 1000).toString().replace('.', '-'),
Oh sorry, now it's done 😃

2022-08-23 15:12 UTC, RahulKasireddy commented on src/Socket/messages-recv.ts
> +				id: (new Date().getTime() / 1000).toString().replace('.', '-'),
@adiwajshing Please update my PR😊

2022-08-29 16:12 UTC, officialdittaz commented
dane done dane done wae kapan dadine iki cuk :v

2022-09-05 05:23 UTC, RahulKasireddy commented
Hi @adiwajshing 👋

2022-09-12 10:41 UTC, ibnusyawall commented
Wow, its work

https://user-images.githubusercontent.com/46734417/189633601-2b91c621-a20e-41de-8e73-313c62f745e1.mp4

2022-09-13 08:55 UTC, merged