feat: support poll message on sendMessage method
adiwajshing/Baileys pull request #2290
Opened 2022-10-24 08:27 UTC by hansputera

## Changelog
1. Add poll message support on `.sendMessage` method
2. Change `.replaceAll` to `.replace` (see https://github.com/adiwajshing/Baileys/commit/a9161c9aa681c84da521676c7a0806ed7d1af796)

## Poll Message Code Example
```ts
await client.sendMessage(whatsapp jid here, {
 poolName: 'testtest',
 poolValues: ['test123', 'test231'],
});
```

## Screenshots
![image](https://user-images.githubusercontent.com/47862061/197392485-86baeaf0-b091-4659-afd4-cea6e43e497d.png)

2022-10-24 09:14 UTC, hansputera reviewed
correction: `poll`, not `pool`

2022-10-24 20:31 UTC, Salientekill commented
Já foi adicionado a baileys? Ou a gente que tem que fazer as alterações?

2022-10-24 23:36 UTC, hansputera commented
> Já foi adicionado a baileys? Ou a gente que tem que fazer as alterações?

This feature isn't available in `@adiwajshing/baileys` now, so I sent this PR to add it

2022-10-25 01:38 UTC, azudindaem commented
Not working for some devices.. This PR is not complete even we can send poll but we can't get poll update.. pretty useless. hopefully this poll will be available to the public soon

2022-10-25 08:39 UTC, SamPandey001 commented
> Not working for some devices.. This PR is not complete even we can send poll but we can't get poll update.. pretty useless. hopefully this poll will be available to the public soon

+1

2022-10-25 09:47 UTC, hansputera commented
> Not working for some devices.. This PR is not complete even we can send poll but we can't get poll update.. pretty useless. hopefully this poll will be available to the public soon

Yes, I think so, this may not work for some devices. In addition, we can receive the poll updates, but only from other users' polls.

2022-10-26 02:10 UTC, azudindaem commented
> Is it possible to force the user to only mark one option in the survey?

selectable_options_count = 1

* Number of options that can be selected. 0 for unlimited options

2022-10-26 21:04 UTC, undefined-60 commented
> Não está funcionando para alguns dispositivos.. Este PR não está completo, mesmo que possamos enviar enquetes, mas não podemos obter atualização de enquetes.. bastante inútil. Espero que esta enquete esteja disponível ao público em breve

Exatamente isso, você pode enviar a enquete mais se não conseguir pegar as atualizações então não vale muito a pena.

2022-10-27 04:11 UTC, SheIITear commented
> Not working for some devices.. This PR is not complete even we can send poll but we can't get poll update.. pretty useless. hopefully this poll will be available to the public soon

It is possible to get poll updates.

https://github.com/adiwajshing/Baileys/issues/2215#issuecomment-1292885678

2022-10-27 10:22 UTC, hansputera commented
> > Not working for some devices.. This PR is not complete even we can send poll but we can't get poll update.. pretty useless. hopefully this poll will be available to the public soon
> 
> It is possible to get poll updates.
> 
> [#2215 (comment)](https://github.com/adiwajshing/Baileys/issues/2215#issuecomment-1292885678)

I'm still curious how do you get the encKey? When I debug the `pollCreationMessage`, and check the encKey, it's just an empty Buffer. Well, in `pollUpdateMessage`, encKey is not listed. Is it possible that we should save the encKey of the `pollCreationMessage`, and use it later for the decrypt process?

2022-10-27 17:54 UTC, SheIITear commented
> > > Not working for some devices.. This PR is not complete even we can send poll but we can't get poll update.. pretty useless. hopefully this poll will be available to the public soon
> > 
> > 
> > It is possible to get poll updates.
> > [#2215 (comment)](https://github.com/adiwajshing/Baileys/issues/2215#issuecomment-1292885678)
> 
> I'm still curious how do you get the encKey? When I debug the `pollCreationMessage`, and check the encKey, it's just an empty Buffer.
> 
> Hm, if the encKey is not empty, should we save the encKey from `pollCreationMessage`, and use it later for the decryption process?

The encKey is a must. Without it for example whatsapp web won't be able to process polls. I have updated my issue comment to contain how to derive the actual decryption key from encKey as I had forgotten that yesterday.

2022-10-27 22:48 UTC, SheIITear commented on src/Utils/messages.ts
> +		m.pollCreationMessage = WAProto.Message.PollCreationMessage.fromObject({
You should generate a safe enc_key that is 32 bytes. This is needed to be able to decrypt / encrypt the poll votes. I also think missing this is the cause why it doesn't work on some devices as someone mentioned in the comments already.

2022-10-28 17:43 UTC, PurpShell commented on src/Utils/messages.ts
> +		m.pollCreationMessage = WAProto.Message.PollCreationMessage.fromObject({
Agreed

2022-10-30 19:48 UTC, 239626 commented
WA v2.22.22.80 is not showing poll, even old polls is not

2022-11-05 05:35 UTC, SheIITear commented
Tested. This pr works fine after adding the encryption key.

![image](https://user-images.githubusercontent.com/62976449/200104198-0668b98e-1117-403c-8ac3-5ab35fb4704f.jpeg)

@hansputera any updates?

2022-11-08 08:08 UTC, azudindaem commented
@hansputera could you please update your pr by adding additional suggestion by @SheIITear 

```typescript
>>include import
import { randomBytes } from 'crypto'

>> include encode
} else if('poll' in message) {
		if(typeof message.poll.selectableCount !== 'number') {
			message.poll.selectableCount = 0
		}

		if(!Array.isArray(message.poll.values)) {
			throw new Boom('Invalid poll values', { statusCode: 400 })
		}

		if(message.poll.selectableCount < 0 || message.poll.selectableCount > message.poll.values.length) {
			throw new Boom(
				`poll.selectableCount in poll should be between 0 and ${
					message.poll.values.length
				} or equal to the items length`, { statusCode: 400 }
			)
		}

		// comment by Shelltear on #2290
		const arr = randomBytes(32)
		m.messageContextInfo = {
			messageSecret: arr //encKey
		}
		
		m.pollCreationMessage = WAProto.Message.PollCreationMessage.fromObject({
			name: message.poll.name,
			selectableOptionsCount: message.poll.selectableCount,
			options: message.poll.values.map(
				value => WAProto.Message.PollCreationMessage.Option.fromObject({
					optionName: value,
				}),
			)
		})
	} else {
``

The rest is good.

2022-11-08 09:02 UTC, hansputera commented
Hello, sorry for the late response as I am preparing for the final school exam. Thanks @SheIITear  for your help and reversing the poll.

reply to @azudindaem: Sure, I'll update the code.

2022-11-08 13:20 UTC, azudindaem commented
@SheIITear has made a clear answer on how to decrypt. Take a look on @PurpShell's gist. We can get encKey from poll creation message. get from store then compare poll option with the decrypt. 

```typescript
 * decrypt a poll message update
 * @param encPayload from the update 
 * @param encIv from the update
 * @param encKey from the original poll
 * @param pollMsgSender sender jid of the pollCreation message
 * @param pollMsgId id of the pollCreation message
 * @param voteMsgSender sender of the pollUpdate message
 * @returns The option or empty array if something went wrong OR everything was unticked

2022-11-08 13:23 UTC, hansputera commented
> @SheIITear has made a clear answer on how to decrypt. Take a look on @PurpShell's gist. We can get encKey from poll creation message. get from store then compare poll option with the decrypt. 
> 
> ```typescript
>  * decrypt a poll message update
>  * @param encPayload from the update 
>  * @param encIv from the update
>  * @param encKey from the original poll
>  * @param pollMsgSender sender jid of the pollCreation message
>  * @param pollMsgId id of the pollCreation message
>  * @param voteMsgSender sender of the pollUpdate message
>  * @returns The option or empty array if something went wrong OR everything was unticked
>  

It means, we need to save/store the encKey from PollCreationMessage, and we can use it later for decrypting process right?

2022-11-08 13:30 UTC, azudindaem commented
Yes. We could use like

const msg = getMessageFromStore('455@s.whatsapp.net', 'HSJHJWH7323HSJSJ') // implement this on your end


```
{
	"key": {
		"remoteJid": "relply-jid@s.whatsapp.net",
		"fromMe": true,
		"id": "msgId from reply"
	},
	"messageTimestamp": 1667913855,
	"pushName": "Pushname",
	"status": 2,
	"message": {
		"pollUpdateMessage": {
			"pollCreationMessageKey": {
				"remoteJid": "owner-jid@s.whatsapp.net",
				"fromMe": false,
				"id": "msgID from poll creation"
			},
			"vote": {
				"encPayload": "sSwOl8r07JOp0ATJ2NlBddT5CJBZxrX1T3JMW9AcO+lbTU+C6tKxMoUgXYV7kME4zAQ=",
				"encIv": "/QkOZm7U+KcntZU6"
			},
			"senderTimestampMs": "1667913855920"
		}
	}
}
```

2022-11-08 20:21 UTC, undefined-60 commented
> Versão WA: `[2, 2242, 6]`/ 2.2242.6
> 
> 1. Não podemos receber o messageSecret / encKey nas atualizações da enquete, então como descriptografá-lo se não tivermos a chave?
>    ![imagem](https://user-images.githubusercontent.com/47862061/200544085-182ab01d-3991-41d7-83dd-60ea7cd3eadb.png)
> 
> Ainda estou confuso btw, alguma idéia/sugestão?

Eu acho que você terá que pegar e salvar quando criar a enquete se possível...

2022-11-09 04:07 UTC, azudindaem commented
@adiwajshing do you have any plan on this pr? better to close and submit only related to poll or you already made your own update

i think we should add this pr and request @PurpShell to create pr for decryption message.

2022-11-09 17:22 UTC, hansputera commented
`getPollUpdateMessage` results:
![image](https://user-images.githubusercontent.com/47862061/200898141-0a8d23d8-a01c-4532-b0a3-a3d0d638a9f1.png)

2022-11-10 00:05 UTC, PurpShell requested changes
Pretty nice implementation.
Though, I would have loved if you just requested the original `pollCreationMessage` instead of a store. As you might know people store their messages in all sorts of places (simply a memory store is inefficient), so just requesting the message would do wonders to make this more approachable and simple.

Also, since we are already running an async context, we should be easily able to get the values from the hash, so it is redundant to return a function (the speed in comparing the hashes is negligible).

2022-11-10 00:05 UTC, PurpShell commented on src/Utils/messages.ts
> +	}
```suggestion
	pollCreationMsg: WAProto.IWebMessageInfo,,
	pollUpdateMsg: WAProto.IWebMessageInfo,
) => {
	if(!pollUpdateMsg.message?.pollUpdateMessage) {
		return undefined
	}

	if(!pollCreationMessage?.message?.messageContextInfo?.messageSecret) {
		return undefined
	}

	const hash = await decryptPollMessageRaw(
		pollCreationMessage.message.messageContextInfo.messageSecret, // encKey
		msg.message?.pollUpdateMessage?.vote?.encPayload!, // enc payload
		msg.message?.pollUpdateMessage?.vote?.encIv!, // enc iv
		jidNormalizedUser(pollCreationMessage.participant!), // sender
		pollCreationMessage.key?.id!, // poll id
		jidNormalizedUser(msg.key.participant!), // voter
	)

	return {
		hash,
		selectedOptions: await comparePollMessage(
			pollCreationMessage.message?.pollCreationMessage?.options?.map(v => v.optionName!)!,
			hash,
		)
	}
```

2022-11-10 01:21 UTC, azudindaem commented
> Pretty nice implementation. Though, I would have loved if you just requested the original `pollCreationMessage` instead of a store. As you might know people store their messages in all sorts of places (simply a memory store is inefficient), so just requesting the message would do wonders to make this more approachable and simple.
> 
> Also, since we are already running an async context, we should be easily able to get the values from the hash, so it is redundant to return a function (the speed in comparing the hashes is negligible).

Agreed

2022-11-10 03:44 UTC, hansputera commented
Like this?
```ts
export const getPollUpdateMessage = async(
	msg: WAProto.IWebMessageInfo,
	pollCreationData: { encKey: Uint8Array; sender: string; options: string[]; },
	withSelectedOptions: boolean = false,
) => {
	if(!msg.message?.pollUpdateMessage || !pollCreationData?.encKey) {
		return undefined
	}

	pollCreationData.sender = msg.message?.pollUpdateMessage?.pollCreationMessageKey?.remoteJid || pollCreationData.sender
	if(!pollCreationData.sender?.length) {
		return undefined
	}

	const hash = await decryptPollMessageRaw(
		pollCreationData.encKey, // encKey
		msg.message?.pollUpdateMessage?.vote?.encPayload!, // enc payload
		msg.message?.pollUpdateMessage?.vote?.encIv!, // enc iv
		jidNormalizedUser(pollCreationData.sender), // sender
		msg.message?.pollUpdateMessage?.pollCreationMessageKey?.id!, // poll id
		jidNormalizedUser(msg.key.participant!), // voter
	)

	return withSelectedOptions ? {
		hash,
		selectedOptions: await comparePollMessage(
			pollCreationData.options || [],
			hash,
		)
	} : { hash }
}
```

2022-11-10 13:19 UTC, undefined-60 commented
> edit: acho que só precisamos de uma mensagem contendo PollUpdateMessage, encKey e poll sender (jid) como parâmetros

Também é válido, assim, não precisaríamos ter que guardar o encKey da enquete original

2022-11-11 02:58 UTC, azudindaem requested changes

2022-11-11 03:11 UTC, hansputera commented on src/Utils/messages.ts
> +		jidNormalizedUser(msg.key.participant!), // voter
Have you tested it?

2022-11-11 03:52 UTC, azudindaem commented on src/Utils/messages.ts
> +		jidNormalizedUser(msg.key.participant!), // voter
my bad.. just tested for non group its not working.. by right poll is only for group as its require participant.. maximum poll option is 12

2022-11-11 04:52 UTC, SheIITear commented on src/Utils/messages.ts
> +		jidNormalizedUser(msg.key.participant!), // voter
> Have you tested it? Because as far as I know, that `msg.key.remoteJid` is in `@g.us` format so it can't be used for decryption. (See https://gist.github.com/PurpShell/44433d21631ff0aefbea57f7b5e31139?permalink_comment_id=4351616#gistcomment-4351616)

For pms remoteJid can be used, its not @g.us. But you have to determine if its a group first because on groups both exists. Just flip the check otherway around so it checks the participant first then if it can't be accessed its private message. For example: ```` msg.key.participant ?? msg.key.remoteJid!````.

2022-11-11 08:01 UTC, hansputera commented
![image](https://user-images.githubusercontent.com/47862061/201293406-df9bc844-ed5e-4bde-9cfc-ae06a9f84744.png)

First choice hash is different

green arrow = 1st choice
red arrow = 2nd choice

2022-11-12 01:06 UTC, hansputera commented on src/Utils/messages.ts
> +		jidNormalizedUser(msg.key.participant!), // voter
> > Have you tested it? Because as far as I know, that `msg.key.remoteJid` is in `@g.us` format so it can't be used for decryption. (See https://gist.github.com/PurpShell/44433d21631ff0aefbea57f7b5e31139?permalink_comment_id=4351616#gistcomment-4351616)
> 
> For pms remoteJid can be used, its not @g.us. But you have to determine if its a group first because on groups both exist. Just flip the check otherway around so it checks the participant first then if it can't be accessed its private message. For example: ` msg.key.participant ?? msg.key.remoteJid!`. The current would always be the first option no matter if group or not hence failing to decrypt on groups, but works in pm.

Hm, after doing more tests in groups. When I tested it on pm, it didn't work. I think, the poll sender's jid is same as the voter's jid. Is that allowed?

2022-11-18 21:01 UTC, rlmoura commented
How can I send polls in groups? Is this code already available in Baileys?

2022-11-19 11:04 UTC, PurpShell commented on src/Utils/messages.ts
> +	const pollCreationMessage = store.messages[
Agreed

2022-11-19 11:11 UTC, PurpShell approved these changes
Looks good, I think you should just add some more JSDoc comments to explain the properties

2022-11-19 11:17 UTC, hansputera commented
> Looks good, I think you should just add some more JSDoc comments to explain the properties

Ok.

2022-11-19 11:29 UTC, hansputera commented
Sorry, I made a mistake. Give me a sec

2022-11-19 11:59 UTC, SheIITear commented
> ![image](https://user-images.githubusercontent.com/47862061/201293406-df9bc844-ed5e-4bde-9cfc-ae06a9f84744.png)
> 
> 
> 
> edit: **Sometimes**, first choice hash is different
> 
> 
> 
> green arrow = 1st choice
> 
> red arrow = 2nd choice

Odd. Can you breakpoint whatsapp web/desktop with same poll, see if voting works and see what happens when it tries to find voted option? Because the hash can't be decoded wrong because the decryption would fail in that case. I think you somehow accidentally passed a wrong string to get hashed. I have never encoutered this even with many tests and different polls.

2022-11-19 12:28 UTC, azudindaem requested changes

2022-11-19 12:28 UTC, azudindaem commented on src/Utils/index.ts
> +export * from './process-message'
Duplicate

2022-11-24 07:20 UTC, hanifdwyputras commented
> > ![image](https://user-images.githubusercontent.com/47862061/201293406-df9bc844-ed5e-4bde-9cfc-ae06a9f84744.png)
> > edit: **Sometimes**, first choice hash is different
> > green arrow = 1st choice
> > red arrow = 2nd choice
> 
> Odd. Can you breakpoint whatsapp web/desktop with same poll, see if voting works and see what happens when it tries to find voted option? Because the hash from the payload can't be wrong as the decryption would fail in that case. I think you somehow accidentally passed a wrong string to get hashed. I have never encountered this even with many tests and different polls.

Nvm, I think the string I want to compare is different from the string in the poll. So, could you please review this PR or give a suggestion?

2022-11-28 04:00 UTC, azudindaem commented
@hanifdwyputras would you mind to close and submit fresh PR only for this poll related. Put aside other update first

2022-12-05 14:16 UTC, rsaisankalp commented
Why is it not merged

2022-12-14 02:02 UTC, closed without merging

2022-12-17 14:35 UTC, rsaisankalp commented
Why is it not merged?

2023-01-07 10:13 UTC, DeveloperNewton commented
UP

Why is it not merged???????????

2023-01-12 02:42 UTC, moskoweb commented
Merge this feature